events { worker_connections 1024; }

http {
  upstream api   { server api:3000;   }
  upstream admin { server admin:3001; }

  server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name api.seudominio.com;

    ssl_certificate     /etc/letsencrypt/live/seudominio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seudominio.com/privkey.pem;

    location / { proxy_pass http://api; proxy_set_header Host $host; }
  }

  server {
    listen 443 ssl;
    server_name admin.seudominio.com;

    ssl_certificate     /etc/letsencrypt/live/seudominio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seudominio.com/privkey.pem;

    location / { proxy_pass http://admin; proxy_set_header Host $host; }
  }
}
